keycloak:
  base-url: http://localhost:7080
  client-id: admin-cli
  username: admin
  password: admin

keycloak-realm:
  base-url: http://localhost:7080
  client-id: health-api
  client-secret: VxxqSGvm8Uqeg9gFUSPfQpRsbxYNbMHs

spring:
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  application:
    name: health
  datasource:
    url: jdbc:postgresql://localhost:5433/bd_health
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: health-api
            client-secret: 7XIJdLe36yyvHXoZfZZIAxDvpwl8MPfc
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${keycloak.base-url}/realms/health
      resource-server:
        jwt:
          issuer-uri: ${keycloak.base-url}/realms/health
  mail:
    host: smtp.gmail.com
    port: 587
    username: tccreembolso@gmail.com
    password: pnyswctoqtveimvb
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org.springframework.security: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
email:
  subject:
    account-created: "Seja bem Vindo ao programa de Rembolso! Redefina sua senha aqui"
  body:
    account-created: "Olá, {user}<br><br>

Sua conta foi criada com sucesso! Para completar o processo, por favor, defina sua senha usando o seguinte link:<br><br>

<a href=\"{resetPasswordLink}\">Redefina sua senha aqui</a><br><br>

Caso o e-mail não apareça, favor verificar a caixa de spam ou lixeira.<br><br>

Se você não solicitou a criação de uma conta, por favor, ignore este e-mail.
"
debug: true


