keycloak:
  base-url: http://localhost:7080
  client-id: admin-cli
  username: admin
  password: admin

keycloak-realm:
  base-url: http://localhost:7080
  client-id: health-api
  client-secret: 5oj3ruNQKn4ShqsHu4rq0vTcfp8TsRZC

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  application:
    name: health
  datasource:
    url: jdbc:postgresql://localhost:5433/bd_health
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: health-api
            client-secret: MuyShRtqmjBHiurKULLdvOi58cInnnRe
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${keycloak.base-url}/realms/health
      resource-server:
        jwt:
          issuer-uri: ${keycloak.base-url}/realms/health
  mail:
    host: smtp.gmail.com
    port: 587
    username: tccreembolso@gmail.com
    password: pnyswctoqtveimvb
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

aws:
  s3:
    access-key-id: AKIAWXFA7CPMM4TP2VXY
    secret-access-key: 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
    region: us-east-1
    bucket-name: mytccbuket

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
email:
  subject:
    account-created: "Seja bem Vindo ao programa de Rembolso! Redefina sua senha aqui"
  body:
    account-created: "Olá, {user}<br><br>

Sua conta foi criada com sucesso! Para completar o processo, por favor, defina sua senha usando o seguinte link:<br><br>

<a href=\"{resetPasswordLink}\">Redefina sua senha aqui</a><br><br>

Caso o e-mail não apareça, favor verificar a caixa de spam ou lixeira.<br><br>

Se você não solicitou a criação de uma conta, por favor, ignore este e-mail.
"

email-status-ok:
  subjects: "Solicitação de Reembolso"
  body: "
    Olá, {user}<br><br>
    Sua Solicitação de Reembolso foi aprovada. Em até 5 dias úteis, você receberá o valor na sua conta salário.<br><br>
    Atenciosamente,<br>
    Sua Empresa "

email-status-rejected:
  subjects: "Solicitação de Reembolso"
  body: "
    Olá, {user}<br><br>
    Sua Solicitação de Reembolso foi reprovada pelo motivo: {observation}. Favor corrigi-los.<br><br>
    Atenciosamente,<br>
    Sua Empresa "


debug: true


