keycloak:
  base-url: http://localhost:7080
  client-id: admin-cli
  username: admin
  password: admin

spring:
  application:
    name: health
  datasource:
    url: jdbc:postgresql://localhost:5433/bd_health
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: health-api
            client-secret: 7XIJdLe36yyvHXoZfZZIAxDvpwl8MPfc
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${keycloak.base-url}/realms/health
      resource-server:
        jwt:
          issuer-uri: ${keycloak.base-url}/realms/health
logging:
  level:
    org.springframework.security: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
debug: true