name: health
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bd_health
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./sql/01-modelo.sql:/docker-entrypoint-initdb.d/01-modelo.sql
    restart: always
    networks:
      - health-network
networks:
  health-network:
    driver: bridge

volumes:
  data:
