package com.reimbursement.health.applications.service;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class EmailServiceTest {

    @Autowired
    private EmailService emailService;

    @Test
    void sendSimpleMessage() {
        emailService.sendResetPasswordCreatedMessage("paulodlima2014@gmail.com", "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJHMVFnN1F4cy02S1JVbG1YZC1DOFFuV0Y4ZzBfOVNDaTVRbUc0U0llWEt3In0.eyJleHAiOjE3MjU4OTcxNjEsImlhdCI6MTcyNTg5Njg2MSwianRpIjoiN2E0YzBjNTktNjg3Yy00MzUyLTk0OWItYzRmMzk4MGQ5ODcwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo3MDgwL3JlYWxtcy9oZWFsdGgiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNmU2YmIyY2UtOWY3YS00MDYwLWJmNjAtNmQ3NmViODFjMTY3IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiaGVhbHRoLWFwaSIsInNpZCI6ImIzNGU0YmVmLTdjOTUtNDE0OS04MDYyLTU2ZGNlMTYzNWZkMiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo0MjAwLyoiLCIqIiwiaHR0cDovL2xvY2FsaG9zdDo0MjAwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy1oZWFsdGgiXX0sInJlc291cmNlX2FjY2VzcyI6eyJoZWFsdGgtYXBpIjp7InJvbGVzIjpbIm1hbmFnZXIiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoibWFuYWdlciB0ZXN0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoibWFuYWdlciIsImdpdmVuX25hbWUiOiJtYW5hZ2VyIiwiZmFtaWx5X25hbWUiOiJ0ZXN0IiwiZW1haWwiOiJtYW5hZ2VyQG1haWwuY29tIn0.EJU7gkzexPyMajC8sjDNBirFh8DHpcTAmRJnRbjrNyYLt6PL1pmABtO9jxGkpuLSiZCh9W5fwi1sbBa_mQXdJZmFI_zwVoc95fhQbIbtQNHV3tZXpBzwcp2O-sW9ohusW2hSipoS4puIYihki3W__i0UX76MNd_TbO9utWKOEFjhAunWqptuG2kiWzxIXz_kT-oDqVllMaLXpvSee0lxZnLHoZsTHftdDDuAgJLM2Ck7I4vybeDJY3gjWSFOShISqrZMvFLJUHMhkgU31rsyN1LFp9lfGZEzOU8mgtkGlvXq5jJxDL3DUk82QUIiANv7K6_ccwlqeugb-OEY2wwapA", "Nome");
    }
}